Bootstrap calls install after cloning/pulling.

diff --git a/.bin/install b/.bin/install
--- a/.bin/install
+++ b/.bin/install
@@ -1,4 +1,21 @@
 #!/bin/bash
 
-sudo swift build --configuration debug
-sudo cp -f .build/debug/xpkg /usr/local/bin/xpkg
+echo "Building."
+swift run builder build
+if [[ $? != 0 ]]
+then
+    echo "Build failed."
+    exit 1
+fi
+
+LOCALBIN=~/.local/bin
+
+echo "Installing links."
+if [[ -e "$LOCALBIN" ]]
+then
+    ln -sf "$ROOT/code/.build/debug/xpkg" "$LOCALBIN/xpkg"
+else
+    sudo ln -sf "$ROOT/code/.build/debug/xpkg" "/usr/local/bin/xpkg"
+fi
+
+echo "Done."
